### ISSUE TITLE
Infinity-loop when starting up application

### ISSUE THREAD

**Issue by khuynhthanhchiluyen** [danielwegener/logback-kafka-appender#99]
I use Spring cloud for configuration.
Here is my `bootstrap.yml`

```yml
spring
  kafka
    bootstrap-servers: localhost:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

```

And this is my `logback.xml`

```xml
<springProperty scope="context" name="kafka" source="spring.kafka.bootstrap-servers"/>
```

My application runs in an infinity loop when starting:

```
[main] INFO  org.apache.kafka.clients.producer.KafkaProducer:1182 - [Producer clientId=producer-16003] Closing the Kafka producer with timeoutMillis = 0 ms.
```

I guess the problem is: Spring cloud created a `KafkaListenerContainerFactory` bean, so does kafka log appender and they have the same name.
Is there anyway for me to fix this ?
